// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_3PYjIaFu_g9xMAmAn5bP0dLciFeGCsQ',
    appId: '1:998566073757:web:bbc338a1b31fc811ea0b74',
    messagingSenderId: '998566073757',
    projectId: 'grainguard-c1dbd',
    authDomain: 'grainguard-c1dbd.firebaseapp.com',
    storageBucket: 'grainguard-c1dbd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZIuHwLJN7Sh68r1SBk5nBTlcReEvdMI0',
    appId: '1:998566073757:android:c0dd953d90a15c50ea0b74',
    messagingSenderId: '998566073757',
    projectId: 'grainguard-c1dbd',
    storageBucket: 'grainguard-c1dbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPVUU5t7EwjczDNgLmKrcMFDzfsbCo02g',
    appId: '1:998566073757:ios:cd927e8e5287138dea0b74',
    messagingSenderId: '998566073757',
    projectId: 'grainguard-c1dbd',
    storageBucket: 'grainguard-c1dbd.firebasestorage.app',
    iosBundleId: 'com.example.grainguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPVUU5t7EwjczDNgLmKrcMFDzfsbCo02g',
    appId: '1:998566073757:ios:cd927e8e5287138dea0b74',
    messagingSenderId: '998566073757',
    projectId: 'grainguard-c1dbd',
    storageBucket: 'grainguard-c1dbd.firebasestorage.app',
    iosBundleId: 'com.example.grainguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_3PYjIaFu_g9xMAmAn5bP0dLciFeGCsQ',
    appId: '1:998566073757:web:ec908d6195aa26e9ea0b74',
    messagingSenderId: '998566073757',
    projectId: 'grainguard-c1dbd',
    authDomain: 'grainguard-c1dbd.firebaseapp.com',
    storageBucket: 'grainguard-c1dbd.firebasestorage.app',
  );

}